require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WorkOrdersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # WorkOrder. As you add validations to WorkOrder, be sure to
  # adjust the attributes here as well.

  let(:valid_attributes) {
    ({route_id: 1, job_id: 1, final_price: 100, notes: "a note", complete: true})
  }

  let(:invalid_attributes) {
    ({route_id: "", job_id: 1, final_price: 100, notes: "a note", complete: true})
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all work_orders as @work_orders" do
      work_order = WorkOrder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:work_orders)).to eq([work_order])
    end
  end

  describe "GET #show" do
    it "assigns the requested work_order as @work_order" do
      work_order = WorkOrder.create! valid_attributes
      get :show, {:id => work_order.to_param}, valid_session
      expect(assigns(:work_order)).to eq(work_order)
    end
  end

  describe "GET #new" do
    xit "assigns a new work_order as @work_order" do
      get :new, {}, valid_session
      expect(assigns(:work_order)).to be_a_new(WorkOrder)
    end
  end

  describe "GET #edit" do
    it "assigns the requested work_order as @work_order" do
      work_order = WorkOrder.create! valid_attributes
      get :edit, {:id => work_order.to_param}, valid_session
      expect(assigns(:work_order)).to eq(work_order)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new WorkOrder" do
        expect {
          post :create, {:work_order => valid_attributes}, valid_session
        }.to change(WorkOrder, :count).by(1)
      end

      it "assigns a newly created work_order as @work_order" do
        post :create, {:work_order => valid_attributes}, valid_session
        expect(assigns(:work_order)).to be_a(WorkOrder)
        expect(assigns(:work_order)).to be_persisted
      end

      it "redirects to the created work_order" do
        post :create, {:work_order => valid_attributes}, valid_session
        expect(response).to redirect_to(WorkOrder.last)
      end
    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved work_order as @work_order" do
        post :create, {:work_order => invalid_attributes}, valid_session
        expect(assigns(:work_order)).to be_a_new(WorkOrder)
      end

      xit "re-renders the 'new' template" do
        post :create, {:work_order => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested work_order" do
        work_order = WorkOrder.create! valid_attributes
        put :update, {:id => work_order.to_param, :work_order => new_attributes}, valid_session
        work_order.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested work_order as @work_order" do
        work_order = WorkOrder.create! valid_attributes
        put :update, {:id => work_order.to_param, :work_order => valid_attributes}, valid_session
        expect(assigns(:work_order)).to eq(work_order)
      end

      it "redirects to the work_order" do
        work_order = WorkOrder.create! valid_attributes
        put :update, {:id => work_order.to_param, :work_order => valid_attributes}, valid_session
        expect(response).to redirect_to(work_order)
      end
    end

    context "with invalid params" do
      it "assigns the work_order as @work_order" do
        work_order = WorkOrder.create! valid_attributes
        put :update, {:id => work_order.to_param, :work_order => invalid_attributes}, valid_session
        expect(assigns(:work_order)).to eq(work_order)
      end

      xit "re-renders the 'edit' template" do
        work_order = WorkOrder.create! valid_attributes
        put :update, {:id => work_order.to_param, :work_order => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested work_order" do
      work_order = WorkOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => work_order.to_param}, valid_session
      }.to change(WorkOrder, :count).by(-1)
    end

    it "redirects to the work_orders list" do
      work_order = WorkOrder.create! valid_attributes
      delete :destroy, {:id => work_order.to_param}, valid_session
      expect(response).to redirect_to(work_orders_url)
    end
  end

end
